language: c

install:
  - sudo apt-get install luarocks
  - mkdir -p ~/.luarocks
  - echo 'rocks_servers = { "http://rocks.moonscript.org" }' > ~/.luarocks/config.lua
  - sudo luarocks install https://rocks.moonscript.org/manifests/olivine-labs/busted-1.11.1-1.rockspec
  - sudo luarocks make

script: busted
